import Head from 'next/head';
import {
  Image,
  Box,
  Container,
  Text,
  Button,
  Grid,
  GridItem,
  Flex,
} from '@chakra-ui/react';
import MotionBirdBox from '../components/MotionBirdBox';
import { priceobject } from '../config/stripe';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bridgetown Bluegrass</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box position='relative' width={'100vw'} height={'auto'} minH={300}>
          <Box
            w={'100%'}
            h={'100%'}
            position='absolute'
            zIndex={-1}
            backgroundColor={'black'}
          >
            <Image
              src={'/images/chansel-bg.png'}
              alt='chansel image'
              sx={{
                objectFit: 'cover',
                minWidth: '100%',
                minH: '100%',
                opacity: 0.3,
              }}
            />
          </Box>

          <Box
            position={'fixed'}
            axis='both'
            marginTop={['10%', null, null, '-10%']}
          >
            <MotionBirdBox />
          </Box>

          <Flex
            py={[4]}
            flexDirection={['column', null, 'row']}
            justifyContent='center'
            alignItems='center'
          >
            <Image
              src='/images/homepage-banner-date.svg'
              alt='saturday may 4th'
              height={'100%'}
              width={'100%'}
              minWidth={[260, null, null, 300]}
              maxWidth={['60vw', null, '100px', '500px']}
              mx={[12, null, 2, 8]}
            />

            <Image
              src='/images/zombie-hand-flat.svg'
              alt='zombie hand wearing banjo picks'
              height={'100%'}
              maxHeight={'600px'}
              width={'100%'}
              minWidth={300}
              maxWidth={['90vw', null, '30%']}
            />

            <Image
              src='/images/homepage-banner-location.svg'
              alt='ucc first congregational church se park and madison'
              height={'100%'}
              width={'100%'}
              minWidth={[260, null, null, 300]}
              maxWidth={['60vw', null, '100px', '500px']}
              mx={[12, null, 2, 8]}
            />
          </Flex>
        </Box>
      </main>
    </>
  );
}
