import Head from 'next/head';
import Image from 'next/image';
import { Image as ChImage } from '@chakra-ui/react';
import { Box, Center, Text, Flex } from '@chakra-ui/react';
import chansel from '../assets/chansel-landing-bg.png';
import MotionBirdBox from '../pages/birds/MotionBirdBox';
import { PageHeadingBoxLg, PageHeadingBoxSm } from '../components/PageHeadingBox';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bridgetown Bluegrass</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box position={'relative'} minWidth={'100%'}>
        <Center
          position={'relative'}
          minW={'100vw'}
          // minH={300}
          bgColor={'black'}
        >
          <Image
            style={{
              minWidth: '100%',
              maxWidth: '100vw',
              objectFit: 'cover',
              opacity: '80%',
            }}
            src={chansel}
            alt='chansel image'
          />
          <Box
            position={'absolute'}
            margin={'auto'}
            w={'100vw'}
            h={'100%'}
            bgGradient={'radial(rgba(0,0,0,0)50%, rgba(0,0,0,1))'}
          >
            <Flex h='100%' flexDirection={'column'} color='white' justifyContent={'center'}>
              <Box textAlign={'center'} mb={[0, null, 2, 4, 8]}>
                <Text
                  sx={{ textTransform: 'uppercase' }}
                  fontSize={['12px', null, '14px', '20px', '24px']}
                  fontWeight={600}
                >
                  The Fifth Annual
                </Text>
                <Text fontSize={['24px', null, '28px', '32px', '36px']}>
                  Bridgetown Bluegrass Folk Festival
                </Text>

                <ChImage
                pt={1}
                  pb={[1, null, 2, 8]}
                  m={'auto'}
                  alignItems={'center'}
                  justifyContent={'center'}
                  w={[32, null, 48, null, 80]}
                  src={'images/may4-2024.svg'}
                  alt='chansel image'
                />
                <Text fontSize={['18px', null, '24px', '28px', '32px']} mb={[1, null, 2]}>
                  First Saturday in May
                </Text>
                <Text
                  sx={{ textTransform: 'uppercase' }}
                  fontSize={['12px', null, '14px', '18px', '20px']}
                  fontWeight={600}
                >
                  UCC's First Congregational Church <br />
                  SW Park and Madison <br />
                  Portland, OR
                </Text>
              </Box>
            </Flex>
            <MotionBirdBox />
            {/* <BBFFCarousel /> */}
          </Box>
        </Center>
      </Box>
    </>
  );
}
