import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Image from 'next/image';
import BBFFCarousel from '../components/BBFFCarousel';
import PageContainer from '../components/PageContainer';
import {  Box, Center, Flex } from '@chakra-ui/react';
import MotionBirdBox from '../components/MotionBirdBox';
import chansel from '../assets/chansel-landing-bg.png';
import MotionBirdFiddle from '../components/MotionBirdFiddle';
import MotionBirdBanjo from '../components/MotionBirdBanjo';
import MotionBirdGuitar from '../components/MotionBirdGuitar';
import MotionBirdMando from '../components/MotionBirdMando';
import MotionBirdBass from '../components/MotionBirdBass';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bridgetown Bluegrass</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Box position={'relative'} minWidth={'100%'}>
          <Center
            position={'relative'}
            minW={'100vw'}
            minH={300}
            bgColor={'black'}
          >
            <Image
              style={{
                minWidth: '100%',
                maxWidth: '100vw',
                objectFit: 'cover',
                opacity: '80%',
              }}
              src={chansel}
              alt='chansel image'
            />
            <Center
              position={'absolute'}
              w={'100%'}
              h={'100%'}
              bgGradient={'radial(rgba(0,0,0,0)50%, rgba(0,0,0,1))'}
            >
          <MotionBirdBox />
              {/* <BBFFCarousel /> */}
            </Center>
          </Center>
        </Box>
      </main>
    </>
  );
}
